server:
  port: 8080

spring:
  application:
    name: ibestyi-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   #eureka-server的地址
  instance:
    instance-id: LAPTOP-LJE5NIQG:ibestyi-gateway:8080
    prefer-ip-address: true

info:
  app.name: ibestyi
  company.name: www.ibestyi.top
  build.artifactId: com.ibestyi.platform.gateway
  build.version: 1.0